### ISSUE TITLE
Support configuration property.

### ISSUE THREAD

**Issue by kawoou** [kawoou/Deli#32]
## How to build
Change the Deli configuration file or include it via command line.

**application-dev.properties:**
```yaml
environment: dev
server:
    url: https://dev.example.com/
```
**deli.yml:**
```yaml
target:
- App

config:
  App:
    - project: App
    - properties:
      - Resources/Common/*.properties
      - Resources/application-dev.properties # override
```
**command line:**
```bash
deli build \
  --property "Resource/application-dev.properties" \
  --property "Resources/Common/*.properties"
```
### 1. Package
**ServerConfig.swift:**
```swift
struct ServerConfig: ConfigProperty {
    let target: String = "server"
    let url: String
}
```
**NetworkManager.swift:**
```swift
final class NetworkManager: Autowired {
    let serverUrl: String

    required init(_ config: ServerConfig) {
        serverUrl = config.url
    }
}
```

### 2. Single (without Validate)
**NetworkManager.swift:**
```swift
final class NetworkManager {
    let serverUrl = AppContext.getProperty("server.url") ?? ""
}
```

### 3. Single (with Validate)
**NetworkManager.swift:**
```swift
final class NetworkManager: Inject {
    let serverUrl = InjectProperty("server.url")
}
```

### 4. Qualifier on Constructor Injection
**UserService.swift:**
```swift
final class UserService: Autowired {
    required init(_/*environment*/ network: NetworkProvider) {
    }
}
```

### 5. Qualifier on Inject
**LibraryFactory.swift:**
```swift
final class LibraryFactory: Inject {
    func getBooks() -> [Book] {
        return Inject([Book].self, qualifierBy: "environment")
    }
}
```

## Reference
- https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
- https://laravel.com/docs/5.7/configuration
- https://github.com/yyvess/Guice-configuration
